import dayjs from 'dayjs';
import dayJsRelativeTimePlugin from 'dayjs/plugin/relativeTime';
import type { Metadata } from 'next';
import { Crimson_Pro, Inter, Roboto_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import Link from 'next/link';
import Script from 'next/script';
import './globals.css';
import mainLayoutClasses from './layout.module.css';

export const crimson_pro = Crimson_Pro({
  subsets: ['latin']
});

// const gentium = Gentium_Book_Plus({
//   subsets: ['latin'],
//   weight: ['400']
// });

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter'
});

export const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono'
});

const satoshi = localFont({
  src: '../public/fonts/satoshi/Satoshi.ttf',
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

dayjs.extend(dayJsRelativeTimePlugin);

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto_mono.variable}`}>
      {/* <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Gentium+Book+Plus&display=swap" rel="stylesheet"></link>
      </head> */}
      <body>
        <header className={mainLayoutClasses.layoutHeader}>
          <Link href="/">
            <h1>BlogLife</h1>
          </Link>
          <nav className="flex gap-x-4">
            <Link href="/" className={`text-link ${mainLayoutClasses.navItem}`}>
              Home
            </Link>
            <Link href="/blogs" className={`text-link ${mainLayoutClasses.navItem}`}>
              Blogs
            </Link>
            <Link href="/img-demo" className={`text-link ${mainLayoutClasses.navItem}`}>
              Image demo
            </Link>
            <Link href="/lazy-loading" className={`text-link ${mainLayoutClasses.navItem}`}>
              Lazy loading
            </Link>
          </nav>
        </header>
        <div className="max-w-[75dvw] mx-auto mt-4">{children}</div>
        {/* https://ionic.io/ionicons/usage */}
        <Script
          type="module"
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
          strategy="beforeInteractive"></Script>
        <Script
          noModule
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
          strategy="beforeInteractive"></Script>
      </body>
    </html>
  );
}
